# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import sensor_cloud
from sensor_cloud.rest import ApiException
from sensor_cloud.models.location_collection__embedded import LocationCollectionEmbedded


class TestLocationCollectionEmbedded(unittest.TestCase):
    """ LocationCollectionEmbedded unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationCollectionEmbedded(self):
        """
        Test LocationCollectionEmbedded
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.location_collection__embedded.LocationCollectionEmbedded()
        pass


if __name__ == '__main__':
    unittest.main()
