# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import sensor_cloud
from sensor_cloud.rest import ApiException
from sensor_cloud.models.location_post import LocationPost


class TestLocationPost(unittest.TestCase):
    """ LocationPost unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationPost(self):
        """
        Test LocationPost
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.location_post.LocationPost()
        pass


if __name__ == '__main__':
    unittest.main()
