# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import sensor_cloud
from sensor_cloud.rest import ApiException
from sensor_cloud.models.sensing_procedure_post import SensingProcedurePost


class TestSensingProcedurePost(unittest.TestCase):
    """ SensingProcedurePost unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensingProcedurePost(self):
        """
        Test SensingProcedurePost
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.sensing_procedure_post.SensingProcedurePost()
        pass


if __name__ == '__main__':
    unittest.main()
