# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiErrorEmbedded(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'User',
        'status': 'float',
        'message': 'str'
    }

    attribute_map = {
        'user': 'user',
        'status': 'status',
        'message': 'message'
    }

    def __init__(self, user=None, status=None, message=None):
        """
        ApiErrorEmbedded - a model defined in Swagger
        """

        self._user = None
        self._status = None
        self._message = None

        if user is not None:
          self.user = user
        if status is not None:
          self.status = status
        if message is not None:
          self.message = message

    @property
    def user(self):
        """
        Gets the user of this ApiErrorEmbedded.

        :return: The user of this ApiErrorEmbedded.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """
        Sets the user of this ApiErrorEmbedded.

        :param user: The user of this ApiErrorEmbedded.
        :type: User
        """

        self._user = user

    @property
    def status(self):
        """
        Gets the status of this ApiErrorEmbedded.

        :return: The status of this ApiErrorEmbedded.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this ApiErrorEmbedded.

        :param status: The status of this ApiErrorEmbedded.
        :type: float
        """

        self._status = status

    @property
    def message(self):
        """
        Gets the message of this ApiErrorEmbedded.

        :return: The message of this ApiErrorEmbedded.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this ApiErrorEmbedded.

        :param message: The message of this ApiErrorEmbedded.
        :type: str
        """

        self._message = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiErrorEmbedded):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
