# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CollectionPut(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'organisationid': 'str',
        'groupids': 'list[str]',
        'public': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'organisationid': 'organisationid',
        'groupids': 'groupids',
        'public': 'public'
    }

    def __init__(self, id=None, name=None, organisationid=None, groupids=None, public=None):
        """
        CollectionPut - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._organisationid = None
        self._groupids = None
        self._public = None

        self.id = id
        self.name = name
        self.organisationid = organisationid
        if groupids is not None:
          self.groupids = groupids
        if public is not None:
          self.public = public

    @property
    def id(self):
        """
        Gets the id of this CollectionPut.

        :return: The id of this CollectionPut.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CollectionPut.

        :param id: The id of this CollectionPut.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this CollectionPut.

        :return: The name of this CollectionPut.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CollectionPut.

        :param name: The name of this CollectionPut.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def organisationid(self):
        """
        Gets the organisationid of this CollectionPut.

        :return: The organisationid of this CollectionPut.
        :rtype: str
        """
        return self._organisationid

    @organisationid.setter
    def organisationid(self, organisationid):
        """
        Sets the organisationid of this CollectionPut.

        :param organisationid: The organisationid of this CollectionPut.
        :type: str
        """
        if organisationid is None:
            raise ValueError("Invalid value for `organisationid`, must not be `None`")

        self._organisationid = organisationid

    @property
    def groupids(self):
        """
        Gets the groupids of this CollectionPut.
        A list of group identifiers for which this stream will be a member.

        :return: The groupids of this CollectionPut.
        :rtype: list[str]
        """
        return self._groupids

    @groupids.setter
    def groupids(self, groupids):
        """
        Sets the groupids of this CollectionPut.
        A list of group identifiers for which this stream will be a member.

        :param groupids: The groupids of this CollectionPut.
        :type: list[str]
        """

        self._groupids = groupids

    @property
    def public(self):
        """
        Gets the public of this CollectionPut.

        :return: The public of this CollectionPut.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """
        Sets the public of this CollectionPut.

        :param public: The public of this CollectionPut.
        :type: bool
        """

        self._public = public

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CollectionPut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
