# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GroupPost(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'organisationid': 'str',
        'description': 'str',
        'groupids': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'organisationid': 'organisationid',
        'description': 'description',
        'groupids': 'groupids'
    }

    def __init__(self, id=None, name=None, organisationid=None, description=None, groupids=None):
        """
        GroupPost - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._organisationid = None
        self._description = None
        self._groupids = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if organisationid is not None:
          self.organisationid = organisationid
        if description is not None:
          self.description = description
        if groupids is not None:
          self.groupids = groupids

    @property
    def id(self):
        """
        Gets the id of this GroupPost.

        :return: The id of this GroupPost.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this GroupPost.

        :param id: The id of this GroupPost.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this GroupPost.

        :return: The name of this GroupPost.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this GroupPost.

        :param name: The name of this GroupPost.
        :type: str
        """

        self._name = name

    @property
    def organisationid(self):
        """
        Gets the organisationid of this GroupPost.

        :return: The organisationid of this GroupPost.
        :rtype: str
        """
        return self._organisationid

    @organisationid.setter
    def organisationid(self, organisationid):
        """
        Sets the organisationid of this GroupPost.

        :param organisationid: The organisationid of this GroupPost.
        :type: str
        """

        self._organisationid = organisationid

    @property
    def description(self):
        """
        Gets the description of this GroupPost.

        :return: The description of this GroupPost.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this GroupPost.

        :param description: The description of this GroupPost.
        :type: str
        """

        self._description = description

    @property
    def groupids(self):
        """
        Gets the groupids of this GroupPost.

        :return: The groupids of this GroupPost.
        :rtype: list[str]
        """
        return self._groupids

    @groupids.setter
    def groupids(self, groupids):
        """
        Sets the groupids of this GroupPost.

        :param groupids: The groupids of this GroupPost.
        :type: list[str]
        """

        self._groupids = groupids

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GroupPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
