# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Invitation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'OrganisationLinks',
        'id': 'str',
        'invitedby': 'str',
        'invitedon': 'str',
        'userid': 'str',
        'embedded': 'InvitationEmbedded'
    }

    attribute_map = {
        'links': '_links',
        'id': 'id',
        'invitedby': 'invitedby',
        'invitedon': 'invitedon',
        'userid': 'userid',
        'embedded': '_embedded'
    }

    def __init__(self, links=None, id=None, invitedby=None, invitedon=None, userid=None, embedded=None):
        """
        Invitation - a model defined in Swagger
        """

        self._links = None
        self._id = None
        self._invitedby = None
        self._invitedon = None
        self._userid = None
        self._embedded = None

        if links is not None:
          self.links = links
        if id is not None:
          self.id = id
        if invitedby is not None:
          self.invitedby = invitedby
        if invitedon is not None:
          self.invitedon = invitedon
        if userid is not None:
          self.userid = userid
        if embedded is not None:
          self.embedded = embedded

    @property
    def links(self):
        """
        Gets the links of this Invitation.

        :return: The links of this Invitation.
        :rtype: OrganisationLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this Invitation.

        :param links: The links of this Invitation.
        :type: OrganisationLinks
        """

        self._links = links

    @property
    def id(self):
        """
        Gets the id of this Invitation.
        The unique identifier for the invitation

        :return: The id of this Invitation.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Invitation.
        The unique identifier for the invitation

        :param id: The id of this Invitation.
        :type: str
        """

        self._id = id

    @property
    def invitedby(self):
        """
        Gets the invitedby of this Invitation.
        The user who sent the invitation.

        :return: The invitedby of this Invitation.
        :rtype: str
        """
        return self._invitedby

    @invitedby.setter
    def invitedby(self, invitedby):
        """
        Sets the invitedby of this Invitation.
        The user who sent the invitation.

        :param invitedby: The invitedby of this Invitation.
        :type: str
        """

        self._invitedby = invitedby

    @property
    def invitedon(self):
        """
        Gets the invitedon of this Invitation.
        The date the invitation was sent. (iso8601 format)

        :return: The invitedon of this Invitation.
        :rtype: str
        """
        return self._invitedon

    @invitedon.setter
    def invitedon(self, invitedon):
        """
        Sets the invitedon of this Invitation.
        The date the invitation was sent. (iso8601 format)

        :param invitedon: The invitedon of this Invitation.
        :type: str
        """

        self._invitedon = invitedon

    @property
    def userid(self):
        """
        Gets the userid of this Invitation.
        The userid of the invited user.

        :return: The userid of this Invitation.
        :rtype: str
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """
        Sets the userid of this Invitation.
        The userid of the invited user.

        :param userid: The userid of this Invitation.
        :type: str
        """

        self._userid = userid

    @property
    def embedded(self):
        """
        Gets the embedded of this Invitation.

        :return: The embedded of this Invitation.
        :rtype: InvitationEmbedded
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """
        Sets the embedded of this Invitation.

        :param embedded: The embedded of this Invitation.
        :type: InvitationEmbedded
        """

        self._embedded = embedded

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Invitation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
