# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InvitationPost(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'userid': 'str',
        'organisationid': 'str',
        'roleids': 'list[str]'
    }

    attribute_map = {
        'userid': 'userid',
        'organisationid': 'organisationid',
        'roleids': 'roleids'
    }

    def __init__(self, userid=None, organisationid=None, roleids=None):
        """
        InvitationPost - a model defined in Swagger
        """

        self._userid = None
        self._organisationid = None
        self._roleids = None

        if userid is not None:
          self.userid = userid
        if organisationid is not None:
          self.organisationid = organisationid
        if roleids is not None:
          self.roleids = roleids

    @property
    def userid(self):
        """
        Gets the userid of this InvitationPost.
        The user id of the user to invite.  This must be a valid email address.

        :return: The userid of this InvitationPost.
        :rtype: str
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """
        Sets the userid of this InvitationPost.
        The user id of the user to invite.  This must be a valid email address.

        :param userid: The userid of this InvitationPost.
        :type: str
        """

        self._userid = userid

    @property
    def organisationid(self):
        """
        Gets the organisationid of this InvitationPost.
        The organisation the user is being invited to.

        :return: The organisationid of this InvitationPost.
        :rtype: str
        """
        return self._organisationid

    @organisationid.setter
    def organisationid(self, organisationid):
        """
        Sets the organisationid of this InvitationPost.
        The organisation the user is being invited to.

        :param organisationid: The organisationid of this InvitationPost.
        :type: str
        """

        self._organisationid = organisationid

    @property
    def roleids(self):
        """
        Gets the roleids of this InvitationPost.
        The roles the user will be assigned once the invitation has been accepted.

        :return: The roleids of this InvitationPost.
        :rtype: list[str]
        """
        return self._roleids

    @roleids.setter
    def roleids(self, roleids):
        """
        Sets the roleids of this InvitationPost.
        The roles the user will be assigned once the invitation has been accepted.

        :param roleids: The roleids of this InvitationPost.
        :type: list[str]
        """

        self._roleids = roleids

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InvitationPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
