# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PlatformDeploymentValidTime(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'str',
        'finish': 'str'
    }

    attribute_map = {
        'start': 'start',
        'finish': 'finish'
    }

    def __init__(self, start=None, finish=None):
        """
        PlatformDeploymentValidTime - a model defined in Swagger
        """

        self._start = None
        self._finish = None

        if start is not None:
          self.start = start
        if finish is not None:
          self.finish = finish

    @property
    def start(self):
        """
        Gets the start of this PlatformDeploymentValidTime.

        :return: The start of this PlatformDeploymentValidTime.
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start):
        """
        Sets the start of this PlatformDeploymentValidTime.

        :param start: The start of this PlatformDeploymentValidTime.
        :type: str
        """

        self._start = start

    @property
    def finish(self):
        """
        Gets the finish of this PlatformDeploymentValidTime.

        :return: The finish of this PlatformDeploymentValidTime.
        :rtype: str
        """
        return self._finish

    @finish.setter
    def finish(self, finish):
        """
        Sets the finish of this PlatformDeploymentValidTime.

        :param finish: The finish of this PlatformDeploymentValidTime.
        :type: str
        """

        self._finish = finish

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PlatformDeploymentValidTime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
