# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PlatformDeployment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'valid_time': 'PlatformDeploymentValidTime',
        'locationid': 'str',
        'streamid': 'str'
    }

    attribute_map = {
        'name': 'name',
        'valid_time': 'validTime',
        'locationid': 'locationid',
        'streamid': 'streamid'
    }

    def __init__(self, name=None, valid_time=None, locationid=None, streamid=None):
        """
        PlatformDeployment - a model defined in Swagger
        """

        self._name = None
        self._valid_time = None
        self._locationid = None
        self._streamid = None

        if name is not None:
          self.name = name
        if valid_time is not None:
          self.valid_time = valid_time
        if locationid is not None:
          self.locationid = locationid
        if streamid is not None:
          self.streamid = streamid

    @property
    def name(self):
        """
        Gets the name of this PlatformDeployment.

        :return: The name of this PlatformDeployment.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PlatformDeployment.

        :param name: The name of this PlatformDeployment.
        :type: str
        """

        self._name = name

    @property
    def valid_time(self):
        """
        Gets the valid_time of this PlatformDeployment.

        :return: The valid_time of this PlatformDeployment.
        :rtype: PlatformDeploymentValidTime
        """
        return self._valid_time

    @valid_time.setter
    def valid_time(self, valid_time):
        """
        Sets the valid_time of this PlatformDeployment.

        :param valid_time: The valid_time of this PlatformDeployment.
        :type: PlatformDeploymentValidTime
        """

        self._valid_time = valid_time

    @property
    def locationid(self):
        """
        Gets the locationid of this PlatformDeployment.
        Id of static location

        :return: The locationid of this PlatformDeployment.
        :rtype: str
        """
        return self._locationid

    @locationid.setter
    def locationid(self, locationid):
        """
        Sets the locationid of this PlatformDeployment.
        Id of static location

        :param locationid: The locationid of this PlatformDeployment.
        :type: str
        """

        self._locationid = locationid

    @property
    def streamid(self):
        """
        Gets the streamid of this PlatformDeployment.
        Id of location stream tracking this platform

        :return: The streamid of this PlatformDeployment.
        :rtype: str
        """
        return self._streamid

    @streamid.setter
    def streamid(self, streamid):
        """
        Sets the streamid of this PlatformDeployment.
        Id of location stream tracking this platform

        :param streamid: The streamid of this PlatformDeployment.
        :type: str
        """

        self._streamid = streamid

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PlatformDeployment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
