# coding: utf-8

"""
    Sensor Data API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Role(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'links': 'OrganisationLinks',
        'permissions': 'list[Permission]',
        'type': 'str',
        'implied': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'links': '_links',
        'permissions': 'permissions',
        'type': 'type',
        'implied': 'implied'
    }

    def __init__(self, id=None, links=None, permissions=None, type=None, implied=None):
        """
        Role - a model defined in Swagger
        """

        self._id = None
        self._links = None
        self._permissions = None
        self._type = None
        self._implied = None

        if id is not None:
          self.id = id
        if links is not None:
          self.links = links
        if permissions is not None:
          self.permissions = permissions
        if type is not None:
          self.type = type
        if implied is not None:
          self.implied = implied

    @property
    def id(self):
        """
        Gets the id of this Role.

        :return: The id of this Role.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Role.

        :param id: The id of this Role.
        :type: str
        """

        self._id = id

    @property
    def links(self):
        """
        Gets the links of this Role.

        :return: The links of this Role.
        :rtype: OrganisationLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this Role.

        :param links: The links of this Role.
        :type: OrganisationLinks
        """

        self._links = links

    @property
    def permissions(self):
        """
        Gets the permissions of this Role.

        :return: The permissions of this Role.
        :rtype: list[Permission]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """
        Sets the permissions of this Role.

        :param permissions: The permissions of this Role.
        :type: list[Permission]
        """

        self._permissions = permissions

    @property
    def type(self):
        """
        Gets the type of this Role.

        :return: The type of this Role.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Role.

        :param type: The type of this Role.
        :type: str
        """

        self._type = type

    @property
    def implied(self):
        """
        Gets the implied of this Role.

        :return: The implied of this Role.
        :rtype: bool
        """
        return self._implied

    @implied.setter
    def implied(self, implied):
        """
        Sets the implied of this Role.

        :param implied: The implied of this Role.
        :type: bool
        """

        self._implied = implied

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Role):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
